services:
  pool_sv2:
    image: stratumv2/pool_sv2:main
    container_name: pool_sv2
    stop_signal: SIGINT
    env_file:
      - docker_env
    volumes:
      - ./config/pool-jds-config.toml.template:/app/pool-jds-config.toml.template:ro
      - "${BITCOIN_SOCKET_PATH?}:/root/.bitcoin/node.sock"
    entrypoint: >
      sh -c '
        envsubst < /app/pool-jds-config.toml.template> /app/pool-config.toml &&
        exec /app/pool_sv2
      '
    ports:
      - "3333:3333"
      - "3334:3334"
      - "127.0.0.1:9090:9090"  # Monitoring HTTP API & Prometheus metrics (localhost only)
    restart: unless-stopped
    profiles:
      - pool_and_miner_apps_no_jd
      - pool_apps
      - pool_and_miner_apps

  jd_client_sv2:
    image: stratumv2/jd_client_sv2:main
    container_name: jd_client_sv2
    stop_signal: SIGINT
    env_file:
      - docker_env
    volumes:
      - ./config/jdc-config.toml.template:/app/jdc-config.toml.template:ro
      - "${BITCOIN_SOCKET_PATH?}:/root/.bitcoin/node.sock"
    entrypoint: >
      sh -c '
        envsubst < /app/jdc-config.toml.template> /app/jdc-config.toml &&
        exec /app/jd_client_sv2
      '
    ports:
      - "34265:34265"
      - "9091:9091"  # Monitoring HTTP API & Prometheus metrics
    restart: unless-stopped
    profiles:
      - miner_apps
      - pool_and_miner_apps

  tproxy_sv2:
    image: stratumv2/translator_sv2:main
    container_name: tproxy_sv2
    stop_signal: SIGINT
    env_file:
      - docker_env
    volumes:
      - ./config/translator-proxy-config.toml.template:/app/proxy-config.toml.template:ro
    entrypoint: >
      sh -c '
        envsubst < /app/proxy-config.toml.template > /app/translator-config.toml &&
        exec /app/translator_sv2
      '
    ports:
      - "34255:34255"
      - "9092:9092"  # Monitoring HTTP API & Prometheus metrics
    restart: unless-stopped
    profiles:
      - pool_and_miner_apps_no_jd
      - tproxy
      - miner_apps
      - pool_and_miner_apps

networks:
  sv2_apps:

