[package]
name = "mining_device"
version = "0.1.3"
authors = ["The Stratum V2 Developers"]
edition = "2021"
publish = false
documentation = "https://github.com/stratum-mining/stratum"
readme = "README.md"
homepage = "https://stratumprotocol.org"
repository = "https://github.com/stratum-mining/stratum"
license = "MIT OR Apache-2.0"
keywords = ["stratum", "mining", "bitcoin", "protocol"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "mining_device"
path = "src/lib/mod.rs"

[dependencies]
stratum-common = { git = "https://github.com/stratum-mining/stratum", branch = "main", features = ["with_network_helpers"] }
async-channel = "1.5.1"
buffer_sv2 = { git = "https://github.com/stratum-mining/stratum", branch = "main" }
async-recursion = "0.3.2"
rand = "0.8.4"
futures = "0.3.5"
key-utils = { git = "https://github.com/stratum-mining/stratum", branch = "main" }
clap = { version = "^4.5.4", features = ["derive"] }
tracing = { version = "0.1" }
tracing-subscriber = "0.3"
sha2 = "0.10.6"
tokio = "1.44.1"
primitive-types = "0.13.1"
