[package]
name = "jd_client_sv2"
version = "0.1.0"
authors = ["The Stratum V2 Developers"]
edition = "2021"
description = "Job Declarator Client (JDC) role"
documentation = "https://docs.rs/jd_client"
readme = "README.md"
homepage = "https://stratumprotocol.org"
repository = "https://github.com/stratum-mining/stratum"
license = "MIT OR Apache-2.0"
keywords = ["stratum", "mining", "bitcoin", "protocol"]

[lib]
name = "jd_client_sv2"
path = "src/lib/mod.rs"

[dependencies]
stratum-apps = { workspace = true, features = ["jd_client"] }
async-channel = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
ext-config = { workspace = true }
tracing = { workspace = true }
clap = { workspace = true }
bitcoin_core_sv2 = { workspace = true }
hex = { workspace = true }
hotpath = { workspace = true }

[features]
hotpath = ["hotpath/hotpath"]
hotpath-alloc = ["hotpath", "hotpath/hotpath-alloc"]

