[package]
name = "jd_server"
version = "0.1.3"
authors = ["The Stratum V2 Developers"]
edition = "2021"
description = "Job Declarator Server (JDS) role"
documentation = "https://github.com/stratum-mining/stratum"
readme = "README.md"
homepage = "https://stratumprotocol.org"
repository = "https://github.com/stratum-mining/stratum"
license = "MIT OR Apache-2.0"
keywords = ["stratum", "mining", "bitcoin", "protocol"]


[lib]
name = "jd_server"
path = "src/lib/mod.rs"

[dependencies]
stratum-common = { git = "https://github.com/stratum-mining/stratum", branch = "main", features = ["with_network_helpers"] }
async-channel = "1.5.1"
buffer_sv2 = { git = "https://github.com/stratum-mining/stratum", branch = "main" }
rand = "0.8.4"
tokio = { version = "1.44.1", features = ["full"] }
ext-config = { version = "0.14.0", features = ["toml"], package = "config" }
tracing = { version = "0.1" }
error_handling = { git = "https://github.com/stratum-mining/stratum", branch = "main" }
nohash-hasher = "0.2.0"
serde_json = { version = "1.0", default-features = false, features = ["alloc","raw_value"] }
serde = { version = "1.0.89", features = ["derive", "alloc"], default-features = false }
hashbrown = { version = "0.11", default-features = false, features = ["ahash", "serde"] }
key-utils = { git = "https://github.com/stratum-mining/stratum", branch = "main" }
rpc_sv2 = { git = "https://github.com/stratum-mining/stratum", branch = "main" }
hex = "0.4.3"
config_helpers_sv2 = { git = "https://github.com/stratum-mining/stratum", branch = "main" }
clap = { version = "4.5.39", features = ["derive"] }
