on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Integration Tests

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

    steps:
      - name: Use stable toolchain
        uses: actions/checkout@v4
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install cargo-nextest
        run: cargo install cargo-nextest --locked

      - name: Integration Tests
        run: |
         RUST_BACKTRACE=1 RUST_LOG=debug cargo nextest run --manifest-path=test/integration-tests/Cargo.toml --features sv1 --nocapture