name: Lockfiles

# Trigger the workflow on pull request events for the main branch
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build with locked dependencies
        run: |
          cargo build --manifest-path=pool-apps/Cargo.toml --locked
          cargo build --manifest-path=miner-apps/Cargo.toml --locked
          cargo build --manifest-path=test/integration-tests/Cargo.toml --locked