on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

name: MSRV 1.88 Check

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 0
      CARGO_TARGET_DIR: ${{ github.workspace }}/target
      RUSTFLAGS: -C debuginfo=0

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.88
      - uses: Swatinem/rust-cache@v2
        with:
          cache-bin: "false"
          workspaces: integration-tests -> ../target

      - name: Install capnp dependencies
        run: sudo apt-get install -y capnproto libcapnp-dev

      # Check test compilation without running tests
      - name: Check test compilation for stratum-apps workspace
        run: cargo test --manifest-path=stratum-apps/Cargo.toml --all-features --no-run

      - name: Check test compilation for pool
        run: cargo test --manifest-path=pool-apps/Cargo.toml --all-features --no-run

      - name: Check test compilation for miner applications workspace
        run: cargo test --manifest-path=miner-apps/Cargo.toml --all-features --no-run

      - name: Check test compilation for integration tests workspace
        run: cargo test --manifest-path=integration-tests/Cargo.toml --no-run

      - name: Check test compilation for bitcoin-core-sv2 crate
        run: cargo test --manifest-path=bitcoin-core-sv2/Cargo.toml --no-run
